include:
  - path: ../../compose.networks.yml
services:
  keytag:
    image: apogee-dev/keytag:dev
    user: 0:0
    extends:
      file: ../../compose.base.yml
      service: x-base-service
    environment:
      - APP_OAuthOptions__Authority=${KEYTAG_OIDC_AUTHORITY}
      - APP_OAuthOptions__ClientId=${KEYTAG_OIDC_CLIENT_ID}
      - APP_OAuthOptions__ClientSecret=${KEYTAG_OIDC_CLIENT_SECRET}
      - APP_StorageConfig__RoleArn=${KEYTAG_AWS_ROLE_ARN}
      - APP_StorageConfig__RoleSessionName=${KEYTAG_AWS_ROLE_SESSION_NAME}
      - APP_StorageConfig__S3BucketName=${KEYTAG_AWS_S3_BUCKET_NAME}
      - APP_StorageConfig__S3KeyPrefix=${KEYTAG_AWS_S3_KEY_PREFIX}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - AWS_REGION=${AWS_REGION}
      - HOSTING_DIR=/home/localadmin/hosting-data
      - APP_ScannerConfig__Url=http://keytag-scanner:8080
    labels: 
      - traefik.docker.network=public-proxy
      - traefik.enable=true

      - traefik.http.routers.keytag-backend-blocker-dev.rule=Host(`keytag.internal.apogee-dev.com`) && Path(`/healthcheck/ready`)
      - traefik.http.routers.keytag-backend-blocker-dev.priority=100
      - traefik.http.routers.keytag-backend-blocker-dev.service=noop@internal

      - traefik.http.routers.keytag-dev.entrypoints=websecured
      - traefik.http.routers.keytag-dev.rule=Host(`keytag.internal.apogee-dev.com`)
      - traefik.http.routers.keytag-dev.priority=50
      - traefik.http.routers.keytag-dev.service=keytag-dev
      - traefik.http.routers.keytag-dev.tls=true
      - traefik.http.routers.keytag-dev.tls.certResolver=dns_route53
      - traefik.http.routers.keytag-dev.tls.domains[0].main=*.internal.apogee-dev.com
      - traefik.http.routers.keytag-dev.tls.domains[0].sans=internal.apogee-dev.com

      - traefik.http.services.keytag-dev.loadbalancer.server.port=5000
      - traefik.http.services.keytag-dev.loadbalancer.healthcheck.path=/health/ready
    volumes:
      - ${HOSTING_DIR}/keytag/dev/dpapi-keys:/dpapi-keys
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health/ready || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  keytag-scanner:
    image: apogee-dev/keytag-scanner:dev
    user: 0:0
    extends:
      file: ../../compose.base.yml
      service: x-base-service