- Apps:
    - Public Homepage:
        icon: https://www.apogee-dev.com/fav.png
        href: https://www.apogee-dev.com
        description: Developer Profile
    - Identity Server:
        icon: https://idsrv-1.apogee-dev.com/A_logo_v2.svg
        href: https://idsrv-1.apogee-dev.com
        description: OIDC Auth Provider
    - Proxy Auth Manager:
        icon: https://fwd-auth-manager.internal.apogee-dev.com/web/Traefik_auth_manager.png
        href: https://fwd-auth-manager.internal.apogee-dev.com/home
        description: Forward authentication manager for local Traefik instance.
    - Minecraft Manager:
        icon: minecraft.png
        href: https://mc-manager.internal.apogee-dev.com
        description: minecraft Server Manager
    - Webhook Tester:
        icon: webhook.png
        href: https://offsite.apogee-dev.com/webhook-tester
        description: Webhook Debugger
    - Colloquy:
        icon: https://colloquy.apogee-dev.com/app-logo-128x128.png
        href: https://colloquy.apogee-dev.com
        description: Manage communication across platforms.

- Infrastructure:
    - Traefik:
        icon: traefik.png
        href: http://proxy.internal.apogee-dev.com:8080
        description: Reverse Proxy
        widget:
          type: traefik
          url: http://reverse-proxy:8080
    - Portainer:
        icon: portainer.png
        href: https://portainer.internal.apogee-dev.com:3000
        description: Container Manager
        widget:
          type: portainer
          url: https://portainer:9443 # Standard secure port for Portainer
          env: 3 # Usually 'local' is env 1 or 2, check your setup
          key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
    - Dockge:
        icon: dockge.png
        href: https://dockge.internal.apogee-dev.com:3000
        description: Stack Manager
- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://uptime.internal.apogee-dev.com:3000/status/home-services
        description: Service Monitor
        widget:
          type: uptimekuma
          url: http://uptime:3001
          slug: home-services
    - Grafana:
        icon: grafana.png
        href: https://grafana.internal.apogee-dev.com
        description: Metrics Dashboard
- Data:
    - PgAdmin:
        icon: pgadmin.png
        href: https://pgadmin.internal.apogee-dev.com
        description: Postgres Manager
        # No native widget, just a link
    - Redis Manager:
        icon: redis.png
        href: https://redis.internal.apogee-dev.com
        description: Redis UI
        # No native widget, just a link
    - WebDB Manager:
        icon: webdb.png
        href: https://webdb.internal.apogee-dev.com
        description: WebDB UI
    - Infisical Secrets Server:
        icon: infisical.png
        href: https://secrets.internal.apogee-dev.com:9090
        description: Infisical Secrets Server
